/**
 * Created by Erwin on 2017/4/4 0004.
 *
 */
'use strict';
angular.module('hrss.si.enterprise.directivesModule')
  .controller('treeDemoCtrl', ['$uibModal', '$scope', '$http', '$window', '$timeout', '$log', 'messageBox',
      function ($uibModal, $scope, $http, $window, $timeout, $log, messageBox) {

          $scope.isExtend = false;

          $scope.treeData = [{
              "id": "01",
              "name": "录入档案",
              "fullName": "录入档案",
              "children": [{
                  "id": "C5D7C486A14F4D6BB7FE1B9ED210B7A6",
                  "name": "新建条目",
                  "fullName": "新建条目",
                  "children": [ {
                      "id": "0602",
                      "name": "浏览",
                      "fullName": "浏览",
                      "children": [],
                      "parentid": "06",
                      "isCheck": null,
                      "code": null
                  }, {
                      "id": "0603",
                      "name": "编目",
                      "fullName": "编目",
                      "children": [{
                          "id": "7B94A68F57264BBD95EDFAAB6FCD4EF5",
                          "name": "入库",
                          "fullName": "入库",
                          "children": [],
                          "parentid": "04",
                          "isCheck": null,
                          "code": null
                      }, {
                          "id": "0B4A86F1CEF74444982568F72C61E796",
                          "name": "出库",
                          "fullName": "出库",
                          "children": [],
                          "parentid": "04",
                          "isCheck": null,
                          "code": null
                      }, {
                          "id": "0B4A86F1CEF74444982568F72C61E123",
                          "name": "库房温湿度",
                          "fullName": "库房温湿度",
                          "children": [],
                          "parentid": "04",
                          "isCheck": null,
                          "code": null
                      }],
                      "parentid": "06",
                      "isCheck": null,
                      "code": null
                  }],
                  "parentid": "01",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "C36CE2C0C9CC41AA88072AD16F0FB816",
                  "name": "原件采集",
                  "fullName": "原件采集",
                  "children": [],
                  "parentid": "01",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "05610A178264487F8BDF7CB01AAC7517",
                  "name": "条码挂接",
                  "fullName": "条码挂接",
                  "children": [],
                  "parentid": "01",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "05610A178264487F8BDF7CB01AAC7518",
                  "name": "导入",
                  "fullName": "导入",
                  "children": [],
                  "parentid": "01",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "05610A178264487F8BDF7CB01AAC7519",
                  "name": "导出",
                  "fullName": "导出",
                  "children": [],
                  "parentid": "01",
                  "isCheck": null,
                  "code": null
              }],
              "parentid": null,
              "isCheck": null,
              "code": null
          }, {
              "id": "02",
              "name": "档案管理",
              "fullName": "档案管理",
              "children": [{
                  "id": "18C4C78C64B842AD9B25DBC4DD6DF2FE",
                  "name": "档案移交",
                  "fullName": "档案移交",
                  "children": [],
                  "parentid": "02",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "06E6E366172E48DB8810AC3D2FDE36C7",
                  "name": "档案接收/回退",
                  "fullName": "档案接收/回退",
                  "children": [],
                  "parentid": "02",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "A974D787D3E64C2384D25832B308AB16",
                  "name": "实物借阅登记",
                  "fullName": "实物借阅登记",
                  "children": [],
                  "parentid": "02",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "3AEAC92CB9A24E21A81C7AB33534918E",
                  "name": "实物借阅归还",
                  "fullName": "实物借阅归还",
                  "children": [],
                  "parentid": "02",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "AAC1258BB8C34352944BF55F9C531EE8",
                  "name": "档案鉴定",
                  "fullName": "档案鉴定",
                  "children": [],
                  "parentid": "02",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "5E842315C3CD4D0B9D56F0FD69677CE1",
                  "name": "销毁库内恢复",
                  "fullName": "销毁库内恢复",
                  "children": [],
                  "parentid": "02",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "D676A579976448C98FA9403239E25F96",
                  "name": "回收站内恢复",
                  "fullName": "回收站内恢复",
                  "children": [],
                  "parentid": "02",
                  "isCheck": null,
                  "code": null
              }],
              "parentid": null,
              "isCheck": null,
              "code": null
          }, {
              "id": "03",
              "name": "报表打印",
              "fullName": "报表打印",
              "children": [{
                  "id": "04628E380E334426954DBB452FD84C81",
                  "name": "卷内目录",
                  "fullName": "卷内目录",
                  "children": [],
                  "parentid": "03",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "5DEBAFC5B11F4FEFA7A465A7EA1220B6",
                  "name": "卷内备考表",
                  "fullName": "卷内备考表",
                  "children": [],
                  "parentid": "03",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "84131FD269244C12B760E35DBCCBFDF7",
                  "name": "案卷封面",
                  "fullName": "案卷封面",
                  "children": [],
                  "parentid": "03",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "7DEC54C135E14396A232A6CA07F12FAB",
                  "name": "移交与接收登记表",
                  "fullName": "移交与接收登记表",
                  "children": [],
                  "parentid": "03",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "B74D693F5BF94D7F9EFC9553FA3482E6",
                  "name": "交接单",
                  "fullName": "交接单",
                  "children": [],
                  "parentid": "03",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "E6535F225C0A4DA6A04EF5589AD4FA4E",
                  "name": "归档交接单",
                  "fullName": "归档交接单",
                  "children": [],
                  "parentid": "03",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "FEA7A639AA1344C09FE85AB46E6E76DF",
                  "name": "利用登记单",
                  "fullName": "利用登记单",
                  "children": [],
                  "parentid": "03",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "659A979D652B45EEB02FAC6A64390797",
                  "name": "销毁清册",
                  "fullName": "销毁清册",
                  "children": [],
                  "parentid": "03",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "F5901E76F22141E78D1B58243DCC0E0E",
                  "name": "移交清册",
                  "fullName": "移交清册",
                  "children": [],
                  "parentid": "03",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "9CB60DB944304736BFDCAC564CBD914C",
                  "name": "月(年)统计表",
                  "fullName": "月(年)统计表",
                  "children": [],
                  "parentid": "03",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "944539FEB4F64F9C83AF304C6F85EFB5",
                  "name": "案卷目录",
                  "fullName": "案卷目录",
                  "children": [],
                  "parentid": "03",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "05B1FD931FFC44D3810BAACF6B5CF3A0",
                  "name": "档案盒背脊",
                  "fullName": "档案盒背脊",
                  "children": [],
                  "parentid": "03",
                  "isCheck": null,
                  "code": null
              }],
              "parentid": null,
              "isCheck": null,
              "code": null
          }, {
              "id": "04",
              "name": "库房管理",
              "fullName": "库房管理",
              "children": [{
                  "id": "9FB86796578C495F9A5340F7349F0CCE",
                  "name": "库房维护",
                  "fullName": "库房维护",
                  "children": [],
                  "parentid": "04",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "7B94A68F57264BBD95EDFAAB6FCD4EF5",
                  "name": "入库",
                  "fullName": "入库",
                  "children": [],
                  "parentid": "04",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "0B4A86F1CEF74444982568F72C61E796",
                  "name": "出库",
                  "fullName": "出库",
                  "children": [],
                  "parentid": "04",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "0B4A86F1CEF74444982568F72C61E123",
                  "name": "库房温湿度",
                  "fullName": "库房温湿度",
                  "children": [],
                  "parentid": "04",
                  "isCheck": null,
                  "code": null
              }],
              "parentid": null,
              "isCheck": null,
              "code": null
          }, {
              "id": "05",
              "name": "搜索",
              "fullName": "搜索",
              "children": [{
                  "id": "C00F374CB70A404CB97D3044ABAAB478",
                  "name": "类型搜索",
                  "fullName": "类型搜索",
                  "children": [],
                  "parentid": "05",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "C00F374CB70A404CB97D3044ABAAB479",
                  "name": "查找替换",
                  "fullName": "查找替换",
                  "children": [],
                  "parentid": "05",
                  "isCheck": null,
                  "code": null
              }],
              "parentid": null,
              "isCheck": null,
              "code": null
          }, {
              "id": "06",
              "name": "基本操作",
              "fullName": "基本操作",
              "children": [{
                  "id": "0601",
                  "name": "扫码",
                  "fullName": "扫码",
                  "children": [],
                  "parentid": "06",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "0602",
                  "name": "浏览",
                  "fullName": "浏览",
                  "children": [],
                  "parentid": "06",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "0603",
                  "name": "编目",
                  "fullName": "编目",
                  "children": [],
                  "parentid": "06",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "0604",
                  "name": "修改",
                  "fullName": "修改",
                  "children": [],
                  "parentid": "06",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "0605",
                  "name": "组卷装盒",
                  "fullName": "组卷装盒",
                  "children": [],
                  "parentid": "06",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "0606",
                  "name": "删除",
                  "fullName": "删除",
                  "children": [],
                  "parentid": "06",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "0607",
                  "name": "删除至回收站",
                  "fullName": "删除至回收站",
                  "children": [],
                  "parentid": "06",
                  "isCheck": null,
                  "code": null
              }],
              "parentid": null,
              "isCheck": null,
              "code": null
          }, {
              "id": "07",
              "name": "系统管理",
              "fullName": "系统管理",
              "children": [{
                  "id": "61D256B9FB0B4501A98B3B00DA69C075",
                  "name": "新建文档库",
                  "fullName": "新建文档库",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "4BC29B1D84E345B8B8DCAC62CF6D601D",
                  "name": "修改文档库",
                  "fullName": "修改文档库",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "D812C4387F7543C380264A54DF01BBC9",
                  "name": "定制文档库",
                  "fullName": "定制文档库",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "AE093F209DDC4FAFB0BD30A6D480C60B",
                  "name": "修改模版",
                  "fullName": "修改模版",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "1CA49694DD7E46D7B9ECA460BAB84FB7",
                  "name": "介质管理",
                  "fullName": "介质管理",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "1CA49694DD7E46D7B9ECA460BAB84123",
                  "name": "数据监控",
                  "fullName": "数据监控",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "5A376500D1B1463B99FDA14C42F42C0A",
                  "name": "二级代码管理",
                  "fullName": "二级代码管理",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "C2163ABBBF4D49918F12433D06D6D97B",
                  "name": "实物借阅配置",
                  "fullName": "实物借阅配置",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "B1A2742A9BA24751B5B4EF538EF299CC",
                  "name": "鉴定配置",
                  "fullName": "鉴定配置",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "C7B8B2D0444A48138A99A7D176E6A5BB",
                  "name": "日志管理",
                  "fullName": "日志管理",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "C7B8B2DW444A48138A99A7D176E6A5BB",
                  "name": "用户监控",
                  "fullName": "用户监控",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "C7B8B2DW444A48138A99A7D176E6A588",
                  "name": "主题词维护",
                  "fullName": "主题词维护",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "C7B8B2DW444A48138A99A7D176E6A222",
                  "name": "角色管理",
                  "fullName": "角色管理",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "C7B8B2DW444A48138A99A7D176E6A333",
                  "name": "用户管理",
                  "fullName": "用户管理",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "C7B8B2DW444A48138A99A7D176E6A444",
                  "name": "授权",
                  "fullName": "授权",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "C7B8B2DW444A48138A99A7D176E6A555",
                  "name": "编目配置",
                  "fullName": "编目配置",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "A974D787D3E64C2384D25832B308AB66",
                  "name": "显示配置",
                  "fullName": "显示配置",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "5A2A200EDCB5071DE0532801003C8C4A",
                  "name": "密码修改",
                  "fullName": "密码修改",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "C7B8B2DW444A48138A99QWEDFTGHA555",
                  "name": "数据来源授权",
                  "fullName": "数据来源授权",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }, {
                  "id": "921449ECCBE04432BD09AABFBE1DD379",
                  "name": "盒信息维护",
                  "fullName": "盒信息维护",
                  "children": [],
                  "parentid": "07",
                  "isCheck": null,
                  "code": null
              }],
              "parentid": null,
              "isCheck": null,
              "code": null
          }];

          // $scope.iconObj = {
          //     parentIconOpen: 'glyphicon glyphicon-star',
          //     parentIconClose: 'glyphicon glyphicon-star',
          //     childrenIcon: 'glyphicon glyphicon-star'
          // };

          /**
           * 添加数据
           */
          $scope.addData = function () {
              $scope.treeData[0].children[0].children.push({
                  id: '0103',
                  name: '教授0103',
                  fullName: '2aaa教授10',
                  children: []
              });
              $log.debug('修改完的数据为：', $scope.treeData);
          };

          /**
           * 全部折叠
           */
          $scope.toggleExtend = function () {
              $scope.isExtend = !$scope.isExtend;
          };


          /**
           * 选中数据
           */
          $scope.getSelectNode = function (selectNode) {
              $log.debug('当前选中数据为：', selectNode);
          }

      }]);