# ===================================================================
# 企业服务大厅UI配置 
# ===================================================================
spring:
  profiles: 
    active: dev_cloud
    
#==========================================================
# 单机开发(dev)环境配置
# - db = oracle
# - port = 9000
#==========================================================
---
spring.profiles: dev
spring.profiles.include: appConfig,dev_port

#==========================================================
# 单机云环境集成测试(dev_cloud)环境配置
# - db = oracle
# - port = 9000
#==========================================================
---
spring.profiles: dev_cloud
spring.profiles.include: appConfig,dev_port_cloud,sabarCloud

#==========================================================
# 公用环境配置(应用在所有的环境当中)
#==========================================================
---
spring:
  profiles: appConfig
  
info:
  component: development-platform-study-ui -前台UI
  

#==========================================================
# 开发服务端口
#==========================================================
---
spring:
  profiles: dev_port
  
server:
  port: 9000
  
#测试环境下指定port    
---
spring:
  profiles: dev_port_cloud

server:
  port: 7080

#-----------------------------
# 云环境配置
# -服务自动注册
#-----------------------------
---
spring:
  profiles: sabarCloud
  oauth2: 
    resource:
      jwt:
        keyValue:  |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----  
eureka:
  instance:
#    homePageUrlPath: ${server.contextPath}/
#    statusPageUrlPath: ${server.contextPath}/info
#    healthCheckUrlPath: ${server.contextPath}/health    
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://162.17.57.1:8761/eureka/,http://162.17.57.2:8761/eureka/          
